spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: DivyaPC@01
  jpa:
    hibernate.ddl-auto: update
    generate-ddl : true
    show-sql : true
      
         
   